---
# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false
contact_links:
  - name: AWS NGFW Security Automations Community Support
    url: https://github.com/JuanVilla424/aws-ngfw-security-automations/discussions
    about: Please ask and answer questions here.
  - name: AWS NGFW Security Automations Security Reports
    url: https://juanvilla424.github.io/aws-ngfw-security-automations/SECURITY
    about: Please report security vulnerabilities here.
